### ISSUE TITLE
io.UnsupportedOperation: seek

### ISSUE THREAD

**Issue by lazy-pi1** [uqfoundation/pathos#107]
Hi all,
I am new to parallel python programming and I am trying to run one function in parallel. Previously I tried with multiprocessing library but it threw an error regarding pickling so, I tried with pathos and the code was working. But then all of a sudden it has started giving me this error.  the function definitions are as follows:

from pathos.multiprocessing import ProcessingPool as Pool 
pullParallel = partial(stockPullWithDateLookup, engine, dataTable, fromdate)
pool.map(pullParallel, chunkedMcscrips)

and the pool.map is giving the error. 
Also, stockPullWithDateLookup() is working in the serial mode. So I am not able to identify what exactly went wrong. Any help is appreciated. 

Traceback (most recent call last):
  File "mcEodDataUpdate.py", line 24, in <module>
    loadAllScriptsEodData()
  File "/home/braineater/maangeLLP/dataFetch/mcDataPull.py", line 388, in loadAllScriptsEodData
    pool.map(pullParallel, chunkedMcscrips)
  File "/usr/local/lib/python3.5/dist-packages/pathos/multiprocessing.py", line 136, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "/usr/local/lib/python3.5/dist-packages/multiprocess/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.5/dist-packages/multiprocess/pool.py", line 608, in get
    raise self._value
  File "/usr/local/lib/python3.5/dist-packages/multiprocess/pool.py", line 385, in _handle_tasks
    put(task)
  File "/usr/local/lib/python3.5/dist-packages/multiprocess/connection.py", line 209, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "/usr/local/lib/python3.5/dist-packages/multiprocess/reduction.py", line 53, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/lib/python3.5/pickle.py", line 408, in dump
    self.save(obj)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.5/pickle.py", line 740, in save_tuple
    save(element)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.5/pickle.py", line 725, in save_tuple
    save(element)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.5/pickle.py", line 725, in save_tuple
    save(element)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.5/dist-packages/dill/dill.py", line 1306, in save_function
    obj.__dict__), obj=obj)
  File "/usr/lib/python3.5/pickle.py", line 599, in save_reduce
    save(args)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.5/pickle.py", line 740, in save_tuple
    save(element)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.5/pickle.py", line 725, in save_tuple
    save(element)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.5/dist-packages/dill/dill.py", line 1057, in save_cell
    pickler.save_reduce(_create_cell, (obj.cell_contents,), obj=obj)
  File "/usr/lib/python3.5/pickle.py", line 599, in save_reduce
    save(args)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.5/pickle.py", line 725, in save_tuple
    save(element)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.5/dist-packages/dill/dill.py", line 968, in save_functor
    obj.keywords), obj=obj)
  File "/usr/lib/python3.5/pickle.py", line 599, in save_reduce
    save(args)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.5/pickle.py", line 740, in save_tuple
    save(element)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.5/pickle.py", line 725, in save_tuple
    save(element)
  File "/usr/lib/python3.5/pickle.py", line 520, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.5/pickle.py", line 623, in save_reduce
    save(state)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.5/dist-packages/dill/dill.py", line 841, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.5/pickle.py", line 810, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.5/pickle.py", line 836, in _batch_setitems
    save(v)
  File "/usr/lib/python3.5/pickle.py", line 520, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.5/pickle.py", line 623, in save_reduce
    save(state)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.5/dist-packages/dill/dill.py", line 841, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.5/pickle.py", line 810, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.5/pickle.py", line 836, in _batch_setitems
    save(v)
  File "/usr/lib/python3.5/pickle.py", line 520, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.5/pickle.py", line 623, in save_reduce
    save(state)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.5/dist-packages/dill/dill.py", line 841, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.5/pickle.py", line 810, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.5/pickle.py", line 836, in _batch_setitems
    save(v)
  File "/usr/lib/python3.5/pickle.py", line 520, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.5/pickle.py", line 599, in save_reduce
    save(args)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.5/pickle.py", line 725, in save_tuple
    save(element)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.5/pickle.py", line 770, in save_list
    self._batch_appends(obj)
  File "/usr/lib/python3.5/pickle.py", line 797, in _batch_appends
    save(tmp[0])
  File "/usr/lib/python3.5/pickle.py", line 520, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.5/pickle.py", line 623, in save_reduce
    save(state)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.5/dist-packages/dill/dill.py", line 841, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.5/pickle.py", line 810, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.5/pickle.py", line 836, in _batch_setitems
    save(v)
  File "/usr/lib/python3.5/pickle.py", line 520, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.5/pickle.py", line 623, in save_reduce
    save(state)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.5/dist-packages/dill/dill.py", line 841, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.5/pickle.py", line 810, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.5/pickle.py", line 836, in _batch_setitems
    save(v)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.5/dist-packages/dill/dill.py", line 920, in save_file
    f = _save_file(pickler, obj, open)
  File "/usr/local/lib/python3.5/dist-packages/dill/dill.py", line 894, in _save_file
    position = obj.tell()
io.UnsupportedOperation: seek

**Comment by mmckerns** [comment]
@lazy-pi1: This seems like (from the `UnsupportedOperation` Error, that you are trying to read and write to a file in parallel with different processes.  While this is ok, it can also go badly many ways.  A better choice is often to read from one file, and write to another then rename it to be the old filename. If this isn't what you are doing, then pardon me.   It's hard to tell from your post what exactly you are doing.  What would help is if you can post a simple example that reproduces your error.  Something that I can try, and thus better diagnose it.

Also, there are some tools that can help uncover what the root of the error is.  You can check if it's a pickling problem with `dill.check` and `dill.detect.trace`, however I don't think it is.  It seems to be an issue with working with files in parallel. And in that case, your best bet is either to post a reduced code example that produces the same error... or editing your code to use a strategy like the one I describe above.

**Comment by lazy-pi1** [comment]
@mmckerns: Thanks for prompt reply. 
I am not doing any raw file i/o operations in the parallelized function. 

The parallelized function is fetching a stock data from a website and writing it to the Mysql DB. I am using urllib2 and BeautifulSoup to scrap the data and then writing it to the Mysql DB by using pymysql and sqlalchemy. I am using pandas to store and handle the data. 

I am not able to understand what is causing the problem so I am not able to write a code that can reproduce the problem. So I am posting the complete code here. Please have a look and see if you can identify the problem.

```

# main function

def loadAllScriptsEodData(engine = engine, dataTable = 'scripts_eod_data',fromdate="2000-01-01",todate=pd.to_datetime('today').strftime(format = "%Y-%m-%d")):

	#Load the mc_id and is_listed_on_nse
	try:
		mcscrips1 = engine.connect().execute("SELECT script_id, mc_id, is_listed_on_nse FROM maangeDb.script_info"
										+" where mc_id is not null ORDER BY script_id ASC;").fetchall()
	except Exception as e:
		print(" Something went wrong while trying to read mc_id and is_listed_on_nse Please check that the given table exists and is present in the current DB specified by engine otherwise read through source code")
		print(e)
		return -1
	mcscrips = []
	for scId in mcscrips1:
		mcscrips.append(scId.values())

	## Main fetching process- have parallelized it 
	num_processes = multiprocessing.cpu_count()
	pool = Pool(num_processes)	
	print(num_processes)
	
	#Lets devide entire task in num_processes small tasks
	chunkedMcscrips = []
	ckSize = int(len(mcscrips)/num_processes)
	for i in range(0, len(mcscrips), ckSize):
		chunkedMcscrips.append(mcscrips[i:i+ckSize])

	pullParallel = partial(stockPullWithDateLookup, engine =  engine, dataTable = dataTable, defaultfromdate = fromdate)
	pool.map(pullParallel, chunkedMcscrips)

```
stockPullWithDateLookup funtion
```
def stockPullWithDateLookup(engine, dataTable, defaultfromdate, mcscrips):
	for script_id, mc_id, is_listed_on_nse in mcscrips:
		fromdate1 = defaultfromdate
		if int(is_listed_on_nse)==1:
			exchange="N"
		else:
			exchange = 'B'
	
		#get the last updated date
		a = engine.connect().execute("SELECT date FROM "+ dataTable + " WHERE script_id = '"+ str(script_id) +
									 "' ORDER BY date DESC LIMIT 1;").fetchall()
		if(len(a) != 0):
			a = a[0]
			fromdate1 = pd.to_datetime(a).shift(1, freq='D').strftime("%Y-%m-%d")
			fromdate1 = fromdate1[0]

		#Pull the data from moneyControl
		data = getStockDataFromMC(mc_id,script_id, exchange, fromdate1)
		if type(data) is not str:
			print(script_id)
			#print(data.head())
			writeStockDfToDb(data, engine, dataTable)
		else:
			print(script_id)
			print("Already uptodate or Failed to fetch")
			print("Please check the url"+ data)

```
```
def getStockDataFromMC(mcid,script_id,ex,fromdate = "2000-01-01",todate = datetime.datetime.today().strftime(format = "%Y-%m-%d")):
			
	isSuccess = False

	url="http://www.moneycontrol.com/stocks/hist_stock_result.php?"	
	impformat = "daily"

	#form the url
	url += "sc_id=" + mcid + "&"
	url += "hdn=" + impformat + "&"
	url += "fdt=" + fromdate + "&"
	url += "todt=" + todate + "&"
	url += "ex=" + ex + "&"

	#To store the price data 
	result = pd.DataFrame(columns=['date', 'open', 'high', 'low', 'close', 'volume'])
	
	pn =1
	while True: #While loop to pull all available pages
		
		page = str(pn)
		url1 = url+ "pno=" + page 
		try:
			html = urlopen(url1)
		except HTTPError as e:
			break
		except URLError as e:
			break
		else:
			try:
				html = BeautifulSoup(html, 'lxml')
			except http.client.IncompleteRead as e:
				html = BeautifulSoup(e.partial, 'lxml')
			allRows = html.find('table', {'class':'tblchart'}).find_all('tr')
			if len(allRows[2].find_all('td')) < 6:
				#the data ended!
				break
			else: 
				del allRows[:2]
				for row in allRows:
					col = row.find_all('td')
					tbl = pd.DataFrame([{'date':pd.to_datetime(col[0].get_text(), format = "%d-%m-%Y"), 'open':col[1].get_text(), 'high':col[2].get_text(), 'low':col[3].get_text(), 'close':col[4].get_text(), 'volume':col[5].get_text()}])
					result = result.append(tbl,ignore_index =False)
		pn+=1
	result = result.set_index(keys = ['date'])
	result['script_id'] = script_id
	if pn>1:
		return result
	else:
		return url1

def writeStockDfToDb(data, engine = engine, tblName = 'scripts_eod_data'):
	connection = engine.connect()
	data.to_sql(name = tblName, con= engine, index= True, if_exists='append')
 ```

**Comment by mmckerns** [comment]
@lazy-pi1: Your issue resolved itself?

**Comment by lazy-pi1** [comment]
@mmckerns  I found out the issue was related to the sharing of sqlAlchemy pool with each worker so I shifted to MySQL connector and created one connection in each worker which resolved the issue.  Cheers!

**Comment by mmckerns** [comment]
Ok, thanks for the follow-up.
