### ISSUE TITLE
bdist_wheel upload failes for python3

### ISSUE THREAD

**Issue by thilo-maurer** [uqfoundation/pathos#146]
After
```
pip3 download pathos --no-binary :all:
```
then extracting the package, then
* build good
* upload failes, when using python3 (python2 is fine)

Reason is that in this projects's `setup.py` line 336, argument `classifiers` should be an array, not a tuple. Replacing `(` by `[` fixes the issue.

See log below:
```
root@host:/build/pathos-0.2.2.1.tar.gz.extracted/pathos-0.2.2.1# python3 setup.py bdist_wheel upload -r artifactory
running bdist_wheel
running build
running build_py
copying pathos/info.py -> build/lib/pathos
running build_scripts
installing to build/bdist.linux-ppc64le/wheel
running install
running install_lib
creating build/bdist.linux-ppc64le/wheel
creating build/bdist.linux-ppc64le/wheel/pathos
copying build/lib/pathos/core.py -> build/bdist.linux-ppc64le/wheel/pathos
copying build/lib/pathos/threading.py -> build/bdist.linux-ppc64le/wheel/pathos
copying build/lib/pathos/pp_map.py -> build/bdist.linux-ppc64le/wheel/pathos
copying build/lib/pathos/abstract_launcher.py -> build/bdist.linux-ppc64le/wheel/pathos
copying build/lib/pathos/multiprocessing.py -> build/bdist.linux-ppc64le/wheel/pathos
copying build/lib/pathos/__main__.py -> build/bdist.linux-ppc64le/wheel/pathos
copying build/lib/pathos/pp.py -> build/bdist.linux-ppc64le/wheel/pathos
copying build/lib/pathos/serial.py -> build/bdist.linux-ppc64le/wheel/pathos
copying build/lib/pathos/connection.py -> build/bdist.linux-ppc64le/wheel/pathos
copying build/lib/pathos/_ppserver_config.py -> build/bdist.linux-ppc64le/wheel/pathos
copying build/lib/pathos/info.py -> build/bdist.linux-ppc64le/wheel/pathos
creating build/bdist.linux-ppc64le/wheel/pathos/helpers
copying build/lib/pathos/helpers/mp_helper.py -> build/bdist.linux-ppc64le/wheel/pathos/helpers
copying build/lib/pathos/helpers/pp_helper.py -> build/bdist.linux-ppc64le/wheel/pathos/helpers
copying build/lib/pathos/helpers/__init__.py -> build/bdist.linux-ppc64le/wheel/pathos/helpers
copying build/lib/pathos/server.py -> build/bdist.linux-ppc64le/wheel/pathos
copying build/lib/pathos/portpicker.py -> build/bdist.linux-ppc64le/wheel/pathos
copying build/lib/pathos/parallel.py -> build/bdist.linux-ppc64le/wheel/pathos
copying build/lib/pathos/util.py -> build/bdist.linux-ppc64le/wheel/pathos
copying build/lib/pathos/selector.py -> build/bdist.linux-ppc64le/wheel/pathos
copying build/lib/pathos/hosts.py -> build/bdist.linux-ppc64le/wheel/pathos
creating build/bdist.linux-ppc64le/wheel/pathos/tests
copying build/lib/pathos/tests/test_map.py -> build/bdist.linux-ppc64le/wheel/pathos/tests
copying build/lib/pathos/tests/__main__.py -> build/bdist.linux-ppc64le/wheel/pathos/tests
copying build/lib/pathos/tests/test_mp.py -> build/bdist.linux-ppc64le/wheel/pathos/tests
copying build/lib/pathos/tests/test_pp.py -> build/bdist.linux-ppc64le/wheel/pathos/tests
copying build/lib/pathos/tests/test_with.py -> build/bdist.linux-ppc64le/wheel/pathos/tests
copying build/lib/pathos/tests/test_decorate.py -> build/bdist.linux-ppc64le/wheel/pathos/tests
copying build/lib/pathos/tests/__init__.py -> build/bdist.linux-ppc64le/wheel/pathos/tests
copying build/lib/pathos/tests/test_star.py -> build/bdist.linux-ppc64le/wheel/pathos/tests
copying build/lib/pathos/tests/test_join.py -> build/bdist.linux-ppc64le/wheel/pathos/tests
copying build/lib/pathos/pools.py -> build/bdist.linux-ppc64le/wheel/pathos
copying build/lib/pathos/__init__.py -> build/bdist.linux-ppc64le/wheel/pathos
copying build/lib/pathos/mp_map.py -> build/bdist.linux-ppc64le/wheel/pathos
creating build/bdist.linux-ppc64le/wheel/pathos/secure
copying build/lib/pathos/secure/connection.py -> build/bdist.linux-ppc64le/wheel/pathos/secure
copying build/lib/pathos/secure/tunnel.py -> build/bdist.linux-ppc64le/wheel/pathos/secure
copying build/lib/pathos/secure/__init__.py -> build/bdist.linux-ppc64le/wheel/pathos/secure
copying build/lib/pathos/secure/copier.py -> build/bdist.linux-ppc64le/wheel/pathos/secure
creating build/bdist.linux-ppc64le/wheel/pathos/xmlrpc
copying build/lib/pathos/xmlrpc/server.py -> build/bdist.linux-ppc64le/wheel/pathos/xmlrpc
copying build/lib/pathos/xmlrpc/__init__.py -> build/bdist.linux-ppc64le/wheel/pathos/xmlrpc
copying build/lib/pathos/python.py -> build/bdist.linux-ppc64le/wheel/pathos
copying build/lib/pathos/profile.py -> build/bdist.linux-ppc64le/wheel/pathos
running install_egg_info
running egg_info
writing pathos.egg-info/PKG-INFO
writing dependency_links to pathos.egg-info/dependency_links.txt
writing requirements to pathos.egg-info/requires.txt
writing top-level names to pathos.egg-info/top_level.txt
reading manifest file 'pathos.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pathos.egg-info/SOURCES.txt'
Copying pathos.egg-info to build/bdist.linux-ppc64le/wheel/pathos-0.2.2.1-py3.6.egg-info
running install_scripts
creating build/bdist.linux-ppc64le/wheel/pathos-0.2.2.1.data
creating build/bdist.linux-ppc64le/wheel/pathos-0.2.2.1.data/scripts
copying build/scripts-3.6/pathos_connect -> build/bdist.linux-ppc64le/wheel/pathos-0.2.2.1.data/scripts
copying build/scripts-3.6/portpicker -> build/bdist.linux-ppc64le/wheel/pathos-0.2.2.1.data/scripts
changing mode of build/bdist.linux-ppc64le/wheel/pathos-0.2.2.1.data/scripts/pathos_connect to 755
changing mode of build/bdist.linux-ppc64le/wheel/pathos-0.2.2.1.data/scripts/portpicker to 755
creating build/bdist.linux-ppc64le/wheel/pathos-0.2.2.1.dist-info/WHEEL
creating '/build/pathos-0.2.2.1.tar.gz.extracted/pathos-0.2.2.1/dist/pathos-0.2.2.1-py3-none-any.whl' and adding '.' to it
adding 'pathos/__init__.py'
adding 'pathos/__main__.py'
adding 'pathos/_ppserver_config.py'
adding 'pathos/abstract_launcher.py'
adding 'pathos/connection.py'
adding 'pathos/core.py'
adding 'pathos/hosts.py'
adding 'pathos/info.py'
adding 'pathos/mp_map.py'
adding 'pathos/multiprocessing.py'
adding 'pathos/parallel.py'
adding 'pathos/pools.py'
adding 'pathos/portpicker.py'
adding 'pathos/pp.py'
adding 'pathos/pp_map.py'
adding 'pathos/profile.py'
adding 'pathos/python.py'
adding 'pathos/selector.py'
adding 'pathos/serial.py'
adding 'pathos/server.py'
adding 'pathos/threading.py'
adding 'pathos/util.py'
adding 'pathos/helpers/__init__.py'
adding 'pathos/helpers/mp_helper.py'
adding 'pathos/helpers/pp_helper.py'
adding 'pathos/secure/__init__.py'
adding 'pathos/secure/connection.py'
adding 'pathos/secure/copier.py'
adding 'pathos/secure/tunnel.py'
adding 'pathos/tests/__init__.py'
adding 'pathos/tests/__main__.py'
adding 'pathos/tests/test_decorate.py'
adding 'pathos/tests/test_join.py'
adding 'pathos/tests/test_map.py'
adding 'pathos/tests/test_mp.py'
adding 'pathos/tests/test_pp.py'
adding 'pathos/tests/test_star.py'
adding 'pathos/tests/test_with.py'
adding 'pathos/xmlrpc/__init__.py'
adding 'pathos/xmlrpc/server.py'
adding 'pathos-0.2.2.1.data/scripts/pathos_connect'
adding 'pathos-0.2.2.1.data/scripts/portpicker'
adding 'pathos-0.2.2.1.dist-info/top_level.txt'
adding 'pathos-0.2.2.1.dist-info/WHEEL'
adding 'pathos-0.2.2.1.dist-info/METADATA'
adding 'pathos-0.2.2.1.dist-info/RECORD'
removing build/bdist.linux-ppc64le/wheel
running upload
Traceback (most recent call last):
  File "setup.py", line 392, in <module>
    exec(setup_code)
  File "<string>", line 269, in <module>
  File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 131, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/distutils/command/upload.py", line 64, in run
    self.upload_file(command, pyversion, filename)
  File "/usr/local/lib/python3.6/distutils/command/upload.py", line 162, in upload_file
    body.write(value)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by mmckerns** [comment]
fixed in 6060701520568f6262549b1f5c3cf23a47a04779
