### ISSUE TITLE
Using the process pool leads to error "ImportError: sys.meta_path is None, Python is likely shutting down" at exit

### ISSUE THREAD

**Issue by bluenote10** [uqfoundation/pathos#244]
The following example works, but it leads to an ugly error message when the main process exits:

```python
import pathos

with pathos.pools.ProcessPool(4) as pool:
  ...
```

Output

```
Exception ignored in: <function Pool.__del__ at 0x7f8c7e23d160>
Traceback (most recent call last):
  File "/home/me/some_venv/lib/python3.8/site-packages/multiprocess/pool.py", line 268, in __del__
  File "/home/me/some_venv/lib/python3.8/site-packages/multiprocess/queues.py", line 365, in put
  File "/home/me/some_venv/lib/python3.8/site-packages/multiprocess/reduction.py", line 54, in dumps
  File "/home/me/some_venv/lib/python3.8/site-packages/multiprocess/reduction.py", line 42, in __init__
  File "/home/me/some_venv/lib/python3.8/site-packages/dill/_dill.py", line 573, in __init__
ImportError: sys.meta_path is None, Python is likely shutting down
```

The process return code is 0 though, i.e., it isn't a "real" error/crash.

The involved libraries should be relatively up-to-date.

```
pathos==0.2.9
dill==0.3.5.1
```

**Comment by havardox** [comment]
Happens to me too. This simple program gives me the exact same error:
```
import pathos

with pathos.pools.ProcessPool(4) as pool:
    print("hello world")
```
```
hello world
Exception ignored in: <function Pool.__del__ at 0x0000018B6EFE9AB0>
Traceback (most recent call last):
  File "C:\Users\harald\AppData\Local\pypoetry\Cache\virtualenvs\pcpartfinder-sLasAYUh-py3.10\lib\site-packages\multiprocess\pool.py", line 268, in __del__
  File "C:\Users\harald\AppData\Local\pypoetry\Cache\virtualenvs\pcpartfinder-sLasAYUh-py3.10\lib\site-packages\multiprocess\queues.py", line 375, 
in put
  File "C:\Users\harald\AppData\Local\pypoetry\Cache\virtualenvs\pcpartfinder-sLasAYUh-py3.10\lib\site-packages\multiprocess\reduction.py", line 54, in dumps
  File "C:\Users\harald\AppData\Local\pypoetry\Cache\virtualenvs\pcpartfinder-sLasAYUh-py3.10\lib\site-packages\multiprocess\reduction.py", line 42, in __init__
  File "C:\Users\harald\AppData\Local\pypoetry\Cache\virtualenvs\pcpartfinder-sLasAYUh-py3.10\lib\site-packages\dill\_dill.py", line 573, in __init__
ImportError: sys.meta_path is None, Python is likely shutting down
```
Running Windows 10, pathos 0.2.9, Python 3.10.6

**Comment by xiay-lcw** [comment]
Same here for

```
Python 3.8.10 (default, Jun 22 2022, 20:18:18)
[GCC 9.4.0] on linux
```

pathos 0.2.9

Ubuntu 20.04.5 LTS

**Comment by xiay-lcw** [comment]
Adding manual `pool.close()` call before process exits seems to solve the issue.  Seems like a python resource clean up order thing.

**Comment by mmckerns** [comment]
@xiay-lcw: that makes sense

**Comment by jaanckae** [comment]
This issue still persists. Are there any updates planned?

`Exception ignored in: <function Pool.__del__ at 0x7f5b0a0a7820>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/multiprocess/pool.py", line 268, in __del__
  File "/usr/local/lib/python3.9/dist-packages/multiprocess/queues.py", line 374, in put
  File "/usr/local/lib/python3.9/dist-packages/multiprocess/reduction.py", line 54, in dumps
  File "/usr/local/lib/python3.9/dist-packages/multiprocess/reduction.py", line 42, in __init__
  File "/usr/local/lib/python3.9/dist-packages/dill/_dill.py", line 573, in __init__
ImportError: sys.meta_path is None, Python is likely shutting down`

Manually adding a pool.close() is not possible in my use case.

Thanks in advance
Jasper

**Comment by mmckerns** [comment]
I'm unable to reproduce this error.

I've checked the most recent versions of python 3.7 - 3.11 with the most recent versions of `dill`, `multiprocess`, and `pathos`, and I don't see the error on Ubuntu 16.04 LTS, MacOS 10.14.6, or Windows 8.
```
Python 3.11.0rc2 (main, Sep 15 2022, 12:55:34) [Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pathos
>>> 
>>> with pathos.pools.ProcessPool(4) as pool:
...     print("hello world")
... 
hello world
```

How is the code being run?  In the interpreter? In a file? In a jupyter notebook?

**Comment by jaanckae** [comment]
Running the code (pathos 0.2.9) in an [apptainer](https://apptainer.org) instance with Python 3.9 on Debian

**Comment by jaanckae** [comment]
I'm just looking for a way to continue my workflow. If I can safely proceed with ignoring this bug, then ok. But I'm not entirely sure this will not affect the rest of my code. 

What would be your suggestion in order to use it in combination with apptainer?

**Comment by mmckerns** [comment]
@jaanckae: apparently it's an innocuous error, so you can likely ignore it.  However, I believe you can  use one of the two choices I mentioned above.  Add a `close` or `clear` to the pool within the context.  Try it and let me know if that removes the behavior you are seeing.

**Comment by bluenote10** [comment]
> I'm unable to reproduce this error. [...] How is the code being run? In the interpreter? In a file? In a jupyter notebook?

This happens at the end of the process, so it is best to place the lines of my example in a file.

> Do you expect it to close upon exiting the context?

My natural expectation was that it is calling `close` on the pool context, because implicitly calling "close" is like the number one use case / responsibility of context managers.

In fact I was very surprised to hear that calling `close` manually makes a difference, because I thought that was the purpose of using a context manager in the first place. Would feel a bit unidiomatic if the pattern context manager + manual close would be required as a work-around.

> Currently, it does nothing.

Maybe I'm missing something, but what's the motivation of using a context manager then?

If I understand it correctly, the implications of calling `close` would only affect advanced use cases involving multiple pools. Personally I haven't encountered any such use case, so I'd be biased towards making the standard use case of a single pool behave more intuitively, i.e., `close` it.

**Comment by bluenote10** [comment]
>  How would you feel about a clear instead, which would then give a behavior that more mirrors a context manager for multiprocessing?

Yes that sounds like the most sensible solution. If I understand it correctly it would nicely handle the basic case of a single pool, and it avoid the two rather unexpected behaviours:
- context manager not cleaning up anything (requiring manual clear/close calls)
- succeeding pool usages not working due to being already closed.

In that sense `Process.clear` has more "close-like semantics" then `close` itself ;)

**Comment by mmckerns** [comment]
In testing, adding a `clear` on `__exit__` yields fairly sensible behavior... (or at least, it mimics `multiprocessing` in many but not all cases). However, in certain cases the pool hangs with a context.  So, I need to figure out what's causing it to hang when `clear` is used in `__exit__`.

Just, FYI, as `pathos.pools` are singletons, a with context can be called like this, and the behavior should be no different than if created with a "new" pool:
```
Python 3.7.15 (default, Oct 12 2022, 04:11:53) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pathos.pools as pp
>>> import math
>>> p = pp.ProcessPool()
>>> p.map(math.sin, [1,2])
[0.8414709848078965, 0.9092974268256817]
>>> with p:
...   p.map(math.sin, [1,2])
... 
[0.8414709848078965, 0.9092974268256817]
```
