### ISSUE TITLE
How to run multiple processes in parallel using Pathos?

### ISSUE THREAD

**Issue by avarf** [uqfoundation/pathos#259]
I need to run different functions in parallel, I use below code and it works:
```python
pv_process = multiprocessing.Process(target=self.publish_pvs, args=(time,))
pv_process.start()
        
wind_process = multiprocessing.Process(target=self.publish_winds, args=(time,))
wind_process.start()

load_process = multiprocessing.Process(target=self.publish_loads, args=(time,))
load_process.start()
```

The issue is I need to share an object with these functions and the `multiprocessing.Process` is not supporting passing custom objects to sub-process. I found Pathos which allows me to pass the object that I want but I cannot make it run in parallel and the calls are running in serial. I tried different options (map, imap, amap, etc) but with no success.
```python
def f(a,b):
    time.sleep(a)
    print(f"inside F -- {b}")

p = ParallelPool(nodes=4)

p1 = p.amap(f(3,1), [])
print("....")
p2 = p.amap(f(1,2), [])
p1.ready()
p2.ready()
```

How can I use pathos to call different functions in parallel?

**Comment by avarf** [comment]
# Update
I am continuing to play with different options, below code can run in parallel:
```python
p1 = pathos.helpers.mp.Process(target=f, args=(20, 1))
p1.start()
print("....")
p2 = pathos.helpers.mp.Process(target=f, args=(1, 2))
p2.start()
p1.join()
```
But it acts exactly similar to the `multiprocessing.Process` (which is not strange since it is just a wrapper for `mp.Process`):
```python
conn = dict()
conn["conn"] = rabbitpy.Connection(RMQ_URL)

p1 = pathos.helpers.mp.Process(target=publish_process, args=(conn, 1))
p1.start()
print("....")
p2 = pathos.helpers.mp.Process(target=publish_process, args=(conn, 2))
p2.start()
p1.join()
```
As you can see the object that I am trying to pass is a dictionary of connections to different RMQs and the code is stuck at creating a channel later.

I tried below codes but I got errors regarding pickling the `conn` dictionary:
```python
p = ParallelPool(nodes=4)
p1 = p.amap(publish_process, [(conn, 1)])
p1.start()
print("....")
p2 = p.amap(publish_process, [(conn, 2)])
p2.start()
p1.join()
```

Error:
```logs
Traceback (most recent call last):
  File "/home/user/workspace/enorch/tools/simulator/src/./test-pathos.py", line 126, in <module>
    p1 = p.amap(publish_process, [(conn, 1)])
  File "/home/user/.local/lib/python3.10/site-packages/pathos/parallel.py", line 280, in amap
    tasks = [submit(*task) for task in args]
  File "/home/user/.local/lib/python3.10/site-packages/pathos/parallel.py", line 280, in <listcomp>
    tasks = [submit(*task) for task in args]
  File "/home/user/.local/lib/python3.10/site-packages/pathos/parallel.py", line 272, in submit
    return _pool.submit(f, argz, globals=globals())
  File "/home/user/.local/lib/python3.10/site-packages/ppft/_pp.py", line 475, in submit
    sargs = pickle.dumps(args, self.__pickle_proto)
  File "/home/user/.local/lib/python3.10/site-packages/dill/_dill.py", line 263, in dumps
    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
  File "/home/user/.local/lib/python3.10/site-packages/dill/_dill.py", line 235, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/home/user/.local/lib/python3.10/site-packages/dill/_dill.py", line 394, in dump
    StockPickler.dump(self, obj)
  File "/usr/lib/python3.10/pickle.py", line 487, in dump
    self.save(obj)
  File "/home/user/.local/lib/python3.10/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/lib/python3.10/pickle.py", line 887, in save_tuple
    save(element)
  File "/home/user/.local/lib/python3.10/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/lib/python3.10/pickle.py", line 887, in save_tuple
    save(element)
  File "/home/user/.local/lib/python3.10/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/user/.local/lib/python3.10/site-packages/dill/_dill.py", line 1186, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.10/pickle.py", line 1003, in _batch_setitems
    save(v)
  File "/home/user/.local/lib/python3.10/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.10/pickle.py", line 717, in save_reduce
    save(state)
  File "/home/user/.local/lib/python3.10/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/user/.local/lib/python3.10/site-packages/dill/_dill.py", line 1186, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/home/user/.local/lib/python3.10/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.10/pickle.py", line 717, in save_reduce
    save(state)
  File "/home/user/.local/lib/python3.10/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/user/.local/lib/python3.10/site-packages/dill/_dill.py", line 1186, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/home/user/.local/lib/python3.10/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 578, in save
    rv = reduce(self.proto)
  File "/usr/lib/python3.10/socket.py", line 273, in __getstate__
    raise TypeError(f"cannot pickle {self.__class__.__name__!r} object")
TypeError: cannot pickle 'socket' object
```

**Comment by mmckerns** [comment]
Your code *is* running in asynchronous parallel. At least, from what I can tell in trying it. However, it sounds like you want a `Process` object, for more refined control of how the functions are called in parallel.  I'd suggest you use a `Process` object from `multiprocess`:
```
>>> import pathos.pools as pp
>>> p = pp._ProcessPool()
>>> p.Process
<bound method Pool.Process of <multiprocess.pool.Pool object at 0x1027cd610>>
>>> p
<multiprocess.pool.Pool object at 0x1027cd610>
>>>
>>> from pathos.helpers import mp
>>> mp.Process
<class 'multiprocess.context.Process'>
>>>
>>> import multiprocess
>>> multiprocess.Process
<class 'multiprocess.context.Process'>

```

**Comment by mmckerns** [comment]
If the question is no longer how to run in parallel, then you should close the issue.  With regard to potentially not serializable objects... if you can pickle it, then you can use it in parallel.  So, you might have to use a different serialization variant (e.g. `dill.settings['recurse'] = True`) or `dill.source` (used in  `pathos.pools.ParallelPool`), or refactor your code.  However, if it's a raw socket object you are trying to send in parallel, then that might be difficult...

**Comment by avarf** [comment]
Thank you for your answer.
Yes, I need a process but I couldn't make it work so I was trying different things. The interesting that I found was the way that I pass the arguments to the Process (both in pathos and python multiprocessing) directly affects the execution. If I pass the arguments separately (`args=(conn, 1)` or `[(conn, 1)]` for pathos) it will execute in parallel but if I pass it as part of the function name (`multiprocessing.Process(target=f(20, 1))`) it gets executed in serial. You learn new things every day :)

I was thinking that pathos automatically pickles the input since somewhere in your repo I read that it can serialize anything. As the last question, the serialization variant that you mentioned is a flag that I can pass to pathos, or do I have to use dill separately?

**Comment by mmckerns** [comment]
> it can serialize anything
Almost, but not everything.

if you import `dill`, then change the settings, it's a global change -- so it will affect how `pathos` works.
