### ISSUE TITLE
cannot allocate memory on fork

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/pathos#35]
On a linux cluster with python 2.6.4, pathos/examples/test_mpmap.py fails (and hangs):

```
Evaluate 5 items on 10 proc:
Traceback (most recent call last):
  File "test_mpmap.py", line 24, in <module>
    pool.ncpus = 10
  File "/home/mmckerns/lib/python2.6/site-packages/pathos-0.2a1.dev-py2.6.egg/pathos/multiprocessing.py", line 142, in __set_nodes
    __STATE['pool'] = Pool(nodes)
  File "/home/mmckerns/lib/python2.6/site-packages/processing-0.52_pathos-py2.6-linux-x86_64.egg/processing/pool.py", line 92, in __init__
    w.start()
  File "/home/mmckerns/lib/python2.6/site-packages/processing-0.52_pathos-py2.6-linux-x86_64.egg/processing/process.py", line 96, in start
    self._popen = Popen(self)
  File "/home/mmckerns/lib/python2.6/site-packages/processing-0.52_pathos-py2.6-linux-x86_64.egg/processing/forking.py", line 52, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

However, on mac OSX with python 2.7.8 and python 2.6.9, it works fine.

**Comment by mmckerns** [comment]
Apparently since the move from `processing` to `multiprocessing`, this is no longer an issue.
