### ISSUE TITLE
processing-0.52-pathos.zip not supported for Windows-64 bit

### ISSUE THREAD

**Issue by jazzblue** [uqfoundation/pathos#49]
While trying to **install processing-0.52-pathos.zip** on my Windows-64bit version:

*pip install processing-0.52-pathos.zip*

... I get an error (see below). It seems like Windows-64-bit is not supported.
Are there any plans to support Windows-64 bit?
Thanks.

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "c:\users\<*username*>\appdata\local\temp\pip-rwarpe-build\setup.py", line 210,
 in <module>

    'Programming Language :: Python',

  File "C:\Python27\lib\distutils\core.py", line 151, in setup

    dist.run_commands()

  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command

    cmd_obj.run()

  File "C:\Python27\lib\site-packages\setuptools\command\install.py", line 61, i
n run

    return orig.install.run(self)

  File "C:\Python27\lib\distutils\command\install.py", line 563, in run

    self.run_command('build')

  File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command

    cmd_obj.run()

  File "C:\Python27\lib\distutils\command\build.py", line 127, in run

    self.run_command(cmd_name)

  File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command

    cmd_obj.run()

  File "C:\Python27\lib\site-packages\setuptools\command\build_ext.py", line 54,
 in run

    _build_ext.run(self)

  File "C:\Python27\lib\distutils\command\build_ext.py", line 337, in run

    self.build_extensions()

  File "C:\Python27\lib\distutils\command\build_ext.py", line 446, in build_exte
nsions

    self.build_extension(ext)

  File "C:\Python27\lib\site-packages\setuptools\command\build_ext.py", line 187
, in build_extension

    _build_ext.build_extension(self, ext)

  File "C:\Python27\lib\distutils\command\build_ext.py", line 496, in build_exte
nsion

    depends=ext.depends)

  File "C:\Python27\lib\distutils\msvc9compiler.py", line 473, in compile

    self.initialize()

  File "C:\Python27\lib\distutils\msvc9compiler.py", line 383, in initialize

    vc_env = query_vcvarsall(VERSION, plat_spec)

  File "C:\Python27\lib\distutils\msvc9compiler.py", line 299, in query_vcvarsal
l

    raise ValueError(str(list(result.keys())))

ValueError: [u'path']

----------------------------------------
Cleaning up...
Command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\use
rs\\<*username*>\\appdata\\local\\temp\\pip-rwarpe-build\\setup.py';exec(compile(getat
tr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'ex
ec'))" install --record c:\users\<*username*>\appdata\local\temp\pip-iw7i9v-record\ins
tall-record.txt --single-version-externally-managed --compile failed with error
code 1 in c:\users\<*username*>\appdata\local\temp\pip-rwarpe-build
Storing debug log for failure in C:\Users\<*username*>\pip\pip.log

**Comment by mmckerns** [comment]
Thanks for posting the traceback.  It seems like it might be a `distutils` bug, as detailed here: http://bugs.python.org/issue7511.  Can list what versions of python and your compiler you are using, and see if they fit the affected versions?  Looks like there's a patch.

**Comment by jazzblue** [comment]
I am running Python 2.7.8.
From the log that I have posted it seems like the compiler is *msvc9compiler*. Is this the compiler you are referring to? Thanks.

**Comment by mmckerns** [comment]
Yes.

Since, this is a larger problem (i.e. a python bug), I'm closing the issue.

However, after the upcoming release, I will see what I can do to find a Win64 VM to build on, and build an windows binary that gets around this.
