### ISSUE TITLE
Key Error when trying to run Pool from other python file

### ISSUE THREAD

**Issue by Thiso6** [uqfoundation/pathos#61]
Hi, when I execute this test code, it works fine:
multiprocess.py

    from pathos.pp import ParallelPythonPool as Pool

    class someClass(object):
    
         def __init__(self):
              pass

         def f(self, x):
              return x*x

         def go(self):
              p = Pool(nodes=5)
              print p.map(self.f, [4,5])

     if __name__ == '__main__':
         sc = someClass()
         sc.go()

However, when I want to do this from another file (which is the case in my real program)
test.py

     from multiprocess import someClass

     if __name__ == '__main__':
         sc = someClass()
         sc.go()

I get this error:

An error has occured during the function import
Traceback (most recent call last):
  File "C:\Users\thijss\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\ppworker.py", line 82, in run
    exec __fobj
  File "<string>", line 1, in <module>
ImportError: cannot import name f
A fatal error has occured during the function execution
Traceback (most recent call last):
  File "C:\Users\thijss\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\ppworker.py", line 91, in run
    __f = locals()[__fname]
KeyError: 'f'
An error has occured during the function import
Traceback (most recent call last):
  File "C:\Users\thijss\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\ppworker.py", line 82, in run
    exec __fobj
  File "<string>", line 1, in <module>
ImportError: cannot import name f
A fatal error has occured during the function execution
Traceback (most recent call last):
  File "C:\Users\thijss\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\ppworker.py", line 91, in run
    __f = locals()[__fname]
KeyError: 'f'
[None, None]

Any idea how I can get this fixed? Thanks!

**Comment by mmckerns** [comment]
Basically, the code relies on `dill.source`, and the former method can find the source code and the necessary dependencies, while the latter fails to find the source of all dependencies.  I can reproduce the error.  I'll need to play with it a bit and diagnose.

**Comment by mmckerns** [comment]
I see.  This is not a case I considered, so I'm going to treat it as a feature request.  ParallelPython (`pp`) assumes all imported modules are *installed* modules.  While `dill.source` doesn't make that assumption explicitly, it's also not been extended for all the cases where the object depends on an uninstalled file.  I'll have to keep that in mind as a use case in extending `dill.source`. I also don't recommend putting the `Pool` as part of a class method with the target being another method -- however an increasing number of people do want to do that, so maybe I need to consider that case more strongly.

You might want to try installing your file `multiprocess.py` as a module.  That might allow `pp` to get around this -- although that's not a sure thing.

**Comment by YohanObadia** [comment]
No updates on this issue. Did you figure out another way of handling this instead of installing as a module?
