### ISSUE TITLE
pool.map: random error os.waitpid

### ISSUE THREAD

**Issue by minhhg** [uqfoundation/pathos#72]
Hi,
when I use pathos  pool = mp.ProcessingPool and pool.map on single machine, sometimes I got the following error (see below).  For example, I run the same code multiple times and some of the runs I got the error message even I know the results are  OK. I am sure this is something to do with pathos
How can I fix this?  Thanks

Traceback (most recent call last):
  File "/home/user/miniconda/envs/banks/lib/python2.7/site-packages/processing-0.52_pathos-py2.7-linux-x86_64.egg/processing/finalize.py", line 114, in _runFinalizers
    finalizer()
  File "/home/user/miniconda/envs/banks/lib/python2.7/site-packages/processing-0.52_pathos-py2.7-linux-x86_64.egg/processing/finalize.py", line 54, in __call__
    self._callback(*self._args, **self._kwargs)
  File "/home/user/miniconda/envs/banks/lib/python2.7/site-packages/processing-0.52_pathos-py2.7-linux-x86_64.egg/processing/pool.py", line 325, in _terminatePool
    p.join()
  File "/home/user/miniconda/envs/banks/lib/python2.7/site-packages/processing-0.52_pathos-py2.7-linux-x86_64.egg/processing/process.py", line 114, in join
    res = self._popen.wait()
  File "/home/user/miniconda/envs/banks/lib/python2.7/site-packages/processing-0.52_pathos-py2.7-linux-x86_64.egg/processing/forking.py", line 65, in wait
    return self.poll(0)
  File "/home/user/miniconda/envs/banks/lib/python2.7/site-packages/processing-0.52_pathos-py2.7-linux-x86_64.egg/processing/forking.py", line 69, in poll
    pid, sts = os.waitpid(self.pid, flag)
OSError: [Errno 4] Interrupted system call

**Comment by mmckerns** [comment]
@minhhg: Can you post a little code that triggers the Traceback, so I could potentially reproduce it? I also notice that you are using `processing-0.52-pathos`, which is no longer maintained.  You should upgrade to the `multiprocess` package, found at: https://github.com/uqfoundation/multiprocess.

**Comment by mmckerns** [comment]
I'm going to assume this was fixed by upgrading.
