### ISSUE TITLE
Error using time module

### ISSUE THREAD

**Issue by pmc2010** [uqfoundation/pathos#93]
When I run the following code:

```python
from pathos.multiprocessing import ProcessingPool as Pool
import time

class A(object):
    def __init__(self, njobs=1000):
        self.map = Pool().map
        self.njobs = njobs
        print(time.time())
        self.start()
    def start(self):
        self.result = self.map(self.RunProcess, range(self.njobs))
        return self.result
    def RunProcess(self, i):
        time.sleep(2)
        return i*i

if __name__ == '__main__': 
    myA = A()
    print(myA.result[:11])
    myA.njobs = 3
    myA.start()  
```

I receive an error:
```
Traceback (most recent call last):
  File "...\test_multiprocessing_pathos.py", line 18, in <module>
    myA = A()
  File "...\test_multiprocessing_pathos.py", line 9, in __init__
    self.start()
  File "...\test_multiprocessing_pathos.py", line 11, in start
    self.result = self.map(self.RunProcess, range(self.njobs))
  File "...\lib\site-packages\pathos\multiprocessing.py", line 136, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "...\lib\site-packages\multiprocess\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "...\lib\site-packages\multiprocess\pool.py", line 567, in get
    raise self._value
NameError: global name 'time' is not defined
```

If I remove `time.sleep(2)`, the code works.  But shouldn't I be able to include time in the method I wish to run?

**Comment by mbelmadani** [comment]
I tried your code and I don't get this error:
`~/sandbox/mp$ python pathostest.py 
1480616940.82
`

and if I do ps ux I see:

```
mbelmad+  3309  0.4  0.0 274212 15220 pts/23   Sl+  10:29   0:00 python pathostest.py
mbelmad+  3310  0.0  0.0  52756 11752 pts/23   S+   10:29   0:00 python pathostest.py
mbelmad+  3311  0.0  0.0  53012 11820 pts/23   S+   10:29   0:00 python pathostest.py
mbelmad+  3312  0.0  0.0  53012 11824 pts/23   S+   10:29   0:00 python pathostest.py
mbelmad+  3313  0.0  0.0  53012 11824 pts/23   S+   10:29   0:00 python pathostest.py
mbelmad+  3314  0.0  0.0  53012 11888 pts/23   S+   10:29   0:00 python pathostest.py
mbelmad+  3315  0.0  0.0  53012 11828 pts/23   S+   10:29   0:00 python pathostest.py
mbelmad+  3316  0.0  0.0  53012 11828 pts/23   S+   10:29   0:00 python pathostest.py
mbelmad+  3317  0.0  0.0  53012 11956 pts/23   S+   10:29   0:00 python pathostest.py
```

So things definitely are running in parallel here. 

Maybe check your python and pathos module version? My version of python is 2.7.6 and my version of pathos is 0.2.0

```
>>> import pathos
>>> dir(pathos)
['SCP_Launcher', 'SSH_Launcher', 'SSH_Tunnel', '__author__', '__builtins__', '__doc__', '__file__', '__license__', '__name__', '__package__', '__path__', '__version__', 'absolute_import', 'abstract_launcher', 'citation', 'connection', 'core', 'helpers', 'hosts', 'info', 'license', 'logger', 'multiprocessing', 'parallel', 'pools', 'pp', 'python', 'secure', 'selector', 'serial', 'server', 'threading', 'util']
>>> pathos.__version__
'0.2.0'
```

**Comment by pmc2010** [comment]
Seems to be an issue with Windows.  The script works when I run it on Linux.  I'm using Windows 7 and pathos version 0.2.0.  Any workarounds?

**Comment by mmckerns** [comment]
Sorry this slipped through the cracks.  Is this still an issue?

I think the explanation lies in which namespace the `time` module was imported into.  Some modules, for whatever reason, are not as easily looked up by a serializer -- and `time` is one of those modules. Another thing to note is that non-Windows systems can share objects across process space better than Windows systems.

```
class A(object):
    def __init__(self, njobs=1000):
        import time
        from pathos.pools import ProcessPool as Pool
        self.map = Pool().map
        self.njobs = njobs
        print(time.time())
        self.start()
    def start(self):
        self.result = self.map(self.RunProcess, range(self.njobs))
        return self.result
    def RunProcess(self, i):
        import time
        time.sleep(2)
        return i*i

if __name__ == '__main__':
    myA = A()
    print(myA.result[:11])
    myA.njobs = 3
    myA.start()
```
The above *should* work on Windows.  You might also want to add `multiprocess.freeze_support` in the `if __name__ == '__main__'` block.

Let me know if the above works for you, or this issue can be closed otherwise.

**Comment by pmc2010** [comment]
Yes, that works.  Thank you so much.
