### ISSUE TITLE
error with subprocess

### ISSUE THREAD

**Issue by insomnia9527** [uqfoundation/pathos#94]
Hi,

I want to use `ParallelPool` and `subprocess` together like:

```
from  pathos.pools import ProcessPool, ParallelPool, SerialPool, ThreadPool
import subprocess
import pathos.core
import pathos.connection

def run_call(i):
	p = subprocess.Popen('echo hello', stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
	err = p.communicate()[1]
	p.wait()

def run():
    p=ParallelPool(ncpus=n_processes)
    #p=mp.Pool()
    p.map(run_call, range(100))
    p.close()
    p.join()

```

But I met some error,
```
lis-MacBook-Pro:test_mem li$ python test.py 
An error has occured during the function import
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ppworker.py", line 82, in run
    exec __fobj
  File "<string>", line 647, in <module>
  File "<string>", line 806, in Popen
NameError: name 'mswindows' is not defined
A fatal error has occured during the function execution
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ppworker.py", line 91, in run
    __f = locals()[__fname]
KeyError: 'run_call'
^Z
[33]+  Stopped                 python test.py

```

I read some document, and replace `run_call` with the following one,

```
def run_call(i):
	p=pathos.connection.Pipe()
	p(command='echo hello')
	p.launch()
	p.response()

```

still a error,

```
lis-MacBook-Pro:test_mem li$ python test.py 
An error has occured during the function import
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ppworker.py", line 82, in run
    exec __fobj
  File "<string>", line 13, in <module>
ValueError: Attempted relative import in non-package
A fatal error has occured during the function execution
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ppworker.py", line 91, in run
    __f = locals()[__fname]
KeyError: 'run_call'
^Z
[34]+  Stopped                 python test.py

```

Can you help me?

**Comment by mmckerns** [comment]
Sorry this fell through the cracks somehow.

I believe the issue is that you are shipping `run_call`  but as written not all the variables are defined in scope.  The key is to fully-encapsulate the declaration of all variables. If you rewrite as below (with the import on the inside of `run_call`), it should work.

```
from pathos.pools import ProcessPool, ParallelPool, SerialPool, ThreadPool

def run_call(i):
    from subprocess import Popen, PIPE
    p = Popen('echo hello', stdout=PIPE, stderr=PIPE, shell=True)
    out,err = p.communicate()
    p.wait()
    return out

def run():
    p=ParallelPool(1)
    res = p.map(run_call, range(1))
    p.close()
    p.join()
    print(res)

if __name__ == '__main__':
    run()
```

Let me know if this can be closed.

**Comment by mmckerns** [comment]
I'm assuming that if this doesn't answer your question, you'll let me know by reopening the ticket.
